trigger: none

parameters:
- name: service_connection
  displayName: 'Service Connection' 
  type: string
  default: ''

jobs:
- template: image-generation.yml
  parameters:
    image_type: windows2019
    image_readme_name: Windows2019-Readme.md
    service_connection: ${{ parameters.service_connection }}